# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltexam_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='users_going',
        ),
        migrations.AddField(
            model_name='trip',
            name='users_going',
            field=models.ManyToManyField(related_name='joined_trips', to='beltexam_app.User'),
        ),
    ]
